# Generated by Django 5.0.7 on 2024-08-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        default="", max_length=255, verbose_name="채용포지션"
                    ),
                ),
                (
                    "reward",
                    models.BigIntegerField(default=0, verbose_name="채용보상금"),
                ),
                (
                    "skills",
                    models.CharField(
                        default="", max_length=255, verbose_name="사용기술"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="채용내용")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="회사_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "db_table": "job_posting",
            },
        ),
    ]
